import { useEffect, useMemo, useRef, useState, type ReactElement } from "react";
import { Check, ChevronDown, ChevronRight, Minus } from "lucide-react";
import "./TreeMultiSelect.css";
export type TreeMultiSelectNode = { id: string; label: string; children?: TreeMultiSelectNode[] };
type Props = { label: string; nodes: TreeMultiSelectNode[]; value: Set<string>; onChange: (value: Set<string>) => void; placeholder?: string; className?: string };
const leaves = (n: TreeMultiSelectNode): string[] => n.children?.length ? n.children.flatMap(leaves) : [n.id];
const descendants = (n: TreeMultiSelectNode): string[] => [n.id, ...(n.children?.flatMap(descendants) ?? [])];
function normalize(nodes: TreeMultiSelectNode[], value: Set<string>) { nodes.forEach(n => { if (n.children?.length) { normalize(n.children, value); leaves(n).every(id => value.has(id)) ? value.add(n.id) : value.delete(n.id); } }); }
function Mark({ state }: { state: "checked" | "mixed" | "empty" }) { return <span className={`fl-tree-multi-checkbox ${state}`} aria-hidden="true">{state === "checked" ? <Check size={13} strokeWidth={3} /> : state === "mixed" ? <Minus size={13} strokeWidth={3} /> : null}</span>; }
export function TreeMultiSelect({ label, nodes, value, onChange, placeholder = "全部资源类型", className = "" }: Props) {
  const [open, setOpen] = useState(false); const [expanded, setExpanded] = useState<Set<string>>(() => new Set(nodes.filter(n => n.children?.length).map(n => n.id))); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (e: PointerEvent) => { if (!ref.current?.contains(e.target as Node)) setOpen(false); }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, []);
  const count = useMemo(() => nodes.flatMap(leaves).filter(id => value.has(id)).length, [nodes, value]);
  const toggle = (n: TreeMultiSelectNode) => { const next = new Set(value); const ids = leaves(n); const selected = ids.every(id => value.has(id)); ids.forEach(id => selected ? next.delete(id) : next.add(id)); normalize(nodes, next); onChange(next); };
  const render = (n: TreeMultiSelectNode, depth = 0): ReactElement => { const has = Boolean(n.children?.length); const isExpanded = expanded.has(n.id); const ids = leaves(n); const selected = ids.filter(id => value.has(id)).length; const state = selected === 0 ? "empty" : selected === ids.length ? "checked" : "mixed"; return <div key={n.id} className="fl-tree-multi-node"><div className="fl-tree-multi-row" style={{ paddingLeft: `${10 + depth * 22}px` }}>{has ? <button type="button" className="fl-tree-multi-expand" aria-label={`${isExpanded ? "收起" : "展开"}${n.label}`} onClick={() => setExpanded(cur => { const next = new Set(cur); isExpanded ? next.delete(n.id) : next.add(n.id); return next; })}>{isExpanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</button> : <span className="fl-tree-multi-expand-placeholder" />}<button type="button" className="fl-tree-multi-option" onClick={() => toggle(n)}><Mark state={state} /><span>{n.label}</span></button></div>{has && isExpanded ? n.children?.map(child => render(child, depth + 1)) : null}</div>; };
  return <div ref={ref} className={`fl-tree-multi-select ${className}`}><span className="fl-tree-multi-label">{label}</span><button type="button" className={`fl-tree-multi-trigger ${open ? "open" : ""}`} aria-haspopup="tree" aria-expanded={open} onClick={() => setOpen(v => !v)}><span className={count ? "selected" : "placeholder"}>{count ? `已选 ${count} 项` : placeholder}</span><ChevronDown size={15} /></button>{open ? <div className="fl-tree-multi-menu" role="tree" aria-label={label}>{nodes.map(render)}</div> : null}</div>;
}
export function expandTreeSelection(nodes: TreeMultiSelectNode[], value: Set<string>) { const next = new Set(value); nodes.forEach(n => { if (n.children?.length && value.has(n.id)) leaves(n).forEach(id => next.add(id)); }); return next; }
export function treeNodeIds(nodes: TreeMultiSelectNode[]) { return nodes.flatMap(descendants); }
